language: go

sudo: false

env:
  - DEP_VERSION="0.3.2"


# Version 1.8 messes up the lint checks for travis
go:
  - "1.9"
  - "1.10"

cache:
  directories:
    - $GOPATH/pkg/dep

install:
  - make setup_ci redep

script:
  - make test
  - make lint
