language: go

sudo: false

env:
  global:
    - GO111MODULE=on DEP_VERSION="0.5.3"

go:
  - "1.13"
  - "1.12"
  - "1.11"
  - "1.10"

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - if [ $TRAVIS_GO_VERSION == "1.13" ]; then
      cd v3 && make setup_ci && cd -;
    else
      curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep;
      chmod +x $GOPATH/bin/dep;
    fi

script:
  - if [ $TRAVIS_GO_VERSION == "1.13" ]; then
      go build -mod=readonly ./... && cd v3 && go build -mod=readonly ./... && cd -;
      go mod verify;
      go mod vendor && GO111MODULE=off PATH=$TRAVIS_BUILD_DIR/bin:$PATH make lint;
      rm -rf vendor;
    else
      dep ensure;
    fi
  - cd v3
  - git stash; make build
  - make test
  - "[ $TRAVIS_GO_VERSION != '1.13' ] || make upload_coverage"
